### PR TITLE
Myq

### PR DESCRIPTION
**Pull request by digitaldan**
These are the rest of my changes.  Since the last merge

### CODE REVIEW

**Comment by digitaldan** [comment]
if you are happy with these changes, then you need to squash everything (see http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) and let Thomas know you are ready for a code review.  Let me know if you need any help.

**Comment by computergeek1507** [comment]
@digitaldan I cannot figure out how to squash my commits. I run the "git rebase -i HEAD~33" command but I don't know how to edit the todo file in git bash on windows. Thanks,

**Comment by digitaldan** [comment]
I have never like rebasing for this kinda of stuff, the link I shared above has the cleanest solution I think.  Here's what I would do:

First lets merge the latest changes from openhab.  From the command line do a `git remote -v` you should see something like:

```
origin  https://github.com/openhab/openhab.git (fetch)
origin  https://github.com/openhab/openhab.git (push)
```

The 'orgin' part is just a name, so it could say remote or foobar, doesn't matter.  If you don't have the main openhab master repo listed then add it, I'm calling it 'upstream' for now.

```
 git remote add upstream https://github.com/openhab/openhab.git
```

run  `git remote -v` to make sure its listed.

now we want to fetch all the changes from upstream to your local instance, this won't do any merging.
`git fetch upstream`

Now we want to merge any changes that have happened upstream in the master branch

`git merge upstream/master`

At this point you will probably have two conflicts, one for the binding pom and one for the global config file, this is b/c they have been modified since you last forked, fix them manually and re-add them (git add theFileThatHasBeenChanged).  When you have fixed the co nflicts, commit your changes.

My MyQ branch has this already done if you want me to do a PR, but it might be good for you to do this manually to learn it. 

Now we can squash,  we will "reset" the branch back to the clean state from upstream, any changes that were made (by us) will become uncommited. 
`git reset upstream/master`

if you do a `git status` you will see the MyQ directory is now new and the binding pom file and system config file are modified.  Thats good ;-)

Now we can do a single commit.  If you want to keep doing this in master you can, this might be a good time to commit the changes in a new branch.  In any case, in master (or your new branch) add the bundles/binding/org.openhab.binding.myq using the git add command, then do a git commit.  At this point all of the changes will now be under a single commit and message.

If you need to chat live I'm on google chat (dan@digitaldan.com).

**Comment by digitaldan** [comment]
Actually I realized I did not actually commit my merge!  My MyQ branch should now contained the latest changes from openHAB master.  Let me know if you want a PR or if you want to do the merge yourself.

**Pull request merged**
